### ISSUE TITLE
creditPolicy() stops getting called once link.linkCredit reaches 0

### ISSUE THREAD

**Issue by jacoscaz** [noodlefrenzy/node-amqp10#113]
Hello Michael.

Thank you for your work on this module. I'm implementing a custom `creditPolicy()` for a consumer that, from time to time, needs to throttle incoming messages down to 0 as it's busy dealing with previous ones. However, unless I add at least 1 credit as soon as `link.linkCredit` hits 0, the AMQP client instance stops calling `creditPolicy()` altogether and I find myself unable to throttle incoming messages back up again.

Is this something you'd consider having a look at? Should I approach this issue in a different way?

Thanks for your time.

**Comment by noodlefrenzy** [comment]
You're right - we only call the window policy when the session window gets modified, and the credit policy when the link credit gets modified, so in your case we'd never call them again.

However, we _do_ call them with the session/link object as a parameters, so you could squirrel that away and call addWindow/addCredits yourself at some later point. I think that's the right way to fix this. Let me know if there's some reason that wouldn't work for you.

In the meantime, I'll think about whether it makes sense for us to periodically retry the policy if we hit zero.

**Comment by jacoscaz** [comment]
Right. How would you go about this in presence of multiple links?

I haven't had the time to study the internals of your module, yet, but it
looks like a link is created for each channel. Isn't it?

Thanks for your time.

You're right - we only call the window policy when the session window gets
modified, and the credit policy when the link credit gets modified, so in
your case we'd never call them again.

However, we *do* call them with the session/link object as a parameters, so
you could squirrel that away and call addWindow/addCredits yourself at some
later point. I think that's the right way to fix this. Let me know if
there's some reason that wouldn't work for you.

In the meantime, I'll think about whether it makes sense for us to
periodically retry the policy if we hit zero.

—
Reply to this email directly or view it on GitHub
<https://github.com/noodlefrenzy/node-amqp10/issues/113#issuecomment-113191088>
.

**Comment by noodlefrenzy** [comment]
Well, the way AMQP 1.0 works is a single link between each pair of endpoints, and it can only send or receive messages, not both. Multiple links can exist in the same session, though, so my code starts up a single session (on a single _channel_) and starts all links in there (each with their own _handle_).

So if I were e.g. receiving from an Event Hub with 16 partitions, I would have 16 links open, all in one single session in one single connection. I'm not quite sure what you're asking when you say "how would you go about this...", but I'll assume you're asking "how would you throttle and un-throttle all links". If I'm wrong, feel free to follow up.  Since flow-control can happen via session windows _and_ via link credits, you have two choices:

1. Write a custom session window policy and throttle all links at once via the session window, and store off the session so you can un-throttle all at once with addWindow.
1. When your link credit policy method is called, store off the links into a map, and when you want to un-throttle walk the map and addCredit.

**Comment by jacoscaz** [comment]
Thanks Michael, much appreciated. That was extremely helpful. I'll let you know how it goes. Thanks again.

**Comment by jacoscaz** [comment]
Hello Michael. 

I ended up storing links into a map and implementing a variable `creditFactor` multiplier in each link's policy that determines how much of the `creditQuantum` is actually passed to `link.addCredits()`. 

The `creditFactor` is decreased on reception and increased each time a message consumer calls the appropriate callback, where an additional call to `creditPolicy()` also takes place in case it hasn't been called for a while. I can now throttle down to 0 and back up again with no issues. 

Performance seems to be pretty much the same when testing with over 10k messages.

Thanks again.

**Comment by mbroadst** [comment]
@jacoscaz great to hear, have you by any chance given the master branch a shot? We're working towards a 2.0.0 release, and the more people testing it the better

**Comment by jacoscaz** [comment]
Not yet but I'll happily see what I can do on my testing system. I'll let you guys know over the next few days.

**Comment by mbroadst** [comment]
Much appreciated! I'm going to go ahead and close this ticket, please open it again if you run into any issues.

**Comment by jacoscaz** [comment]
@mbroadst : sorry about the long absence. I should be able to start testing V2.0 in a week or two. What did you end up doing as far as `whether it makes sense for us to periodically retry the policy if we hit zero`? I'll adapt my code as soon as I get around it.

**Comment by mbroadst** [comment]
@jacoscaz credit management is greatly improved in 2.0.0, I think you should have no issue implementing the behavior you opened this ticket for. When messages arrive now if you are in autosettle mode it will "accept" (acknowledge/settle) the message for you and pump the credits based on your creditPolicy/quantum/creditFunction, however you can also set the receiver mode to manual settle mode (you can find an example of this in the qpid integration tests for disposition). This would allow you very fine-grain control over how messages come in to your service

**Comment by jacoscaz** [comment]
Awesome! Thanks for the pointers. I'll get back at you once I get my hands on v2.0.
