### ISSUE TITLE
Bug fix in amqp_client.js

### ISSUE THREAD

**Issue by footmarks-skylar** [noodlefrenzy/node-amqp10#115]
We came across an issue while testing out your library on Azure. Adding this check fixed it. Keep up the great work on this library!

Current (line 353):
    if (self._pendingSends[linkName].length > 0) {
        attach();
    }

Fixed:
    if (self._pendingSends[linkName] && self._pendingSends[linkName].length > 0) {
        attach();
     }

**Comment by mbroadst** [comment]
@footmarks-skylar doh, we caught that in like 4 other locations it seems ;) Thanks for the fix! By the way, have you been using the master branch (i.e. v2.0.0)?

**Comment by footmarks-skylar** [comment]
Nope I forked off at 1.0.3. What's been updated since?

**Comment by mbroadst** [comment]
@footmarks-skylar a whole bunch, primarily that its promisified-by-default, improved code coverage, a few changes in public api (recieve => createReceiver), and some other bugs. I'm working on integrating message disposition currently. I don't have access to the npm registry so I can't publish a fix for e.g. 1.0.4, but I'll merge your fix into 2.0.0 presently, and we can wait for @noodlefrenzy to get back to make a decision on a 1.0.4 release.

**Comment by footmarks-skylar** [comment]
No need. Just apply this to 2 and I'll move up.

**Comment by mbroadst** [comment]
@footmarks-skylar great, would love more people giving feedback on the 2.0.0 stuff :)

**Comment by mbroadst** [comment]
fixed in a9953e1e37c09951ea7111dd2d87937df188aa11
