### ISSUE TITLE
AmqpOverCapacityError on Azure

### ISSUE THREAD

**Issue by footmarks-skylar** [noodlefrenzy/node-amqp10#116]
So I merged your latest source with my fork and it was running perfectly until just now (maybe 45 minutes) and I'm receiving this:

AmqpOverCapacityError: Out of available handles (Max = 255)]
  name: 'AmqpOverCapacityError',
  message: 'Out of available handles (Max = 255)' } 'AmqpOverCapacityError: Out of available handles (Max = 255)

Any help on resolutions would be greatly appreciated. Thanks!

**Comment by mbroadst** [comment]
@footmarks-skylar interesting, that's thrown when we run out of session handles when creating a link. Can you describe your use case a little bit here? It seems that maybe you're creating/destroying many links during operation?

**Comment by footmarks-skylar** [comment]
Yeah, no problem! 

Within our node app, we are establishing several amqp secure connections at startup. These are used from logging to auditing within our system and they vary in throughput. I've been attempting to configure the policy's settings slightly adjusted where I feel issues could be related but so far I've not been able to determine this error being thrown. I do see the connection being disconnected and reconnected quite often and I was able to stop this from happening by fixing the constant idleTimeout setup that was not inconsistently being used between heartbeat and actual timeout. Although this only temporarly fixed the problem and eventually after running for an hour or so the d/c begin to occur again. 

Let me know your thoughts! Thanks guys

**Comment by mbroadst** [comment]
@footmarks-skylar first of all remember that you can run your app with ```DEBUG=amqp*``` before it in order to get a TON of debug data from node-amqp10. It would be interesting to better understand why your app continuously connects and reconnects. Just to clarify, you're not experiencing this problem with 1.0.3, but instead 2.0.0 (in master), correct?

Perhaps you could provide us with a copy of the logs from running the app with DEBUG enabled until the problem occurs?

**Comment by footmarks-skylar** [comment]
Yes, you guys did a great job wrapping the debug module +1 but since the issues are occurring only after published and running for several hours, I held off up until this point adding the debug output on the server. Locally I was still able to catch several breadcrumbs that led to my ultimate fix. Using your latest source and adjusting the way I established multiple connections, ended up fixing it. Thanks for the help!

**Comment by mbroadst** [comment]
@footmarks-skylar okay great! I'll close the issue, please let us know if you experience any other issues
