### ISSUE TITLE
Npm package outdated

### ISSUE THREAD

**Issue by markusahlstrand** [noodlefrenzy/node-amqp10#135]
Seems that the npm package is still 1.0.3 and there has been quite a few changes since then. Could you publish the 2.0.0 version?

Thanks

**Comment by mbroadst** [comment]
Hi Markus,
The 2.0.0 version in master is pretty different than v1.0, and not exactly in a releasable state yet. We've introduced a number of breaking API changes, and want to reserve the right to continue to do that before the release. We're being particular careful with this as the intention is to not make any breaking API changes once released. 

If you'd like to use v2.0.0 you can easily change your dependencies in your package.json to point to:
```
   "amqp10": "noodlefrenzy/node-amqp10#master"
```

**Comment by markusahlstrand** [comment]
Hi Matt,

Thanks for the quick reply. 

Then I know the reasoning behind it. Would you consider 2.0 to be ready for production or should I use v1 for now?

Kind regards,
Markus

**Comment by mbroadst** [comment]
@markusahlstrand well that point is up for debate :smile: I'm currently using it in production, but I'm also able to iterate quickly dependent on bug fixes. So I'm sort of beta-testing the 2.0.0 release currently, and we would absolutely love more people to do this if they are willing. I can say that it's been quite reliable for me so far.

**Comment by markusahlstrand** [comment]
Ok, then I'll continue to use the 2.0 version. 

Thanks
