### ISSUE TITLE
Manage delivery semantics

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#14]
AMQP 1.0 allows a wide range of delivery semantics, including at-most-once, at-least-once, and umm, neither.  This encapsulates all work to manage that state for in-flight messages, and deal with settlement in-flow/out-flow through the processing and sending of ```disposition``` frames.

**Comment by noodlefrenzy** [comment]
Not needed for any of the initial clients, as they all support auto-settle.

**Comment by noodlefrenzy** [comment]
Note that JBoss AMQ seems to support auto-settle, but when you check the queue size it still shows the "settled" messages.  It doesn't re-deliver them, but it might pose a resource problem if it's holding them in memory.  This might require at least the delivery of Disposition frames, even if the full delivery semantics aren't implemented.

**Comment by mbroadst** [comment]
we have pretty robust support for disposition, which I believe meets the criteria here
