### ISSUE TITLE
Not Receiving from Azure Queue

### ISSUE THREAD

**Issue by edwardconnolly** [noodlefrenzy/node-amqp10#152]
Hello. This week I have been unable to receive any messages from my queue. The same code worked last week and I can still successfully receive using the official .NET library against the same queue. 

I'm not sure where to start. Log below. Many thanks.

Fri, 21 Aug 2015 09:28:59 GMT amqp10-client Connecting to amqps://RootManageSharedAccessKey:XXX@XXX.servicebus.windows.net/q-in-log
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Connecting to XXX.servicebus.windows.net:5671 via TLS
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Transitioning from DISCONNECTED to START due to connect
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Sending Header 414d515003010000
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Transitioning from START to IN_SASL due to connected
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Rx: 414d515003010000
Fri, 21 Aug 2015 09:28:59 GMT amqp10-Connection Rx: 0000002702010000005340c01a01e01702b300000005504c41494e0000000845585445524e414c
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Rx: 0000001a02010000005344c00d025000a00857656c636f6d6521
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Sending Header 414d515000010000
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Transitioning from IN_SASL to HDR_SENT due to success
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Rx: 414d515000010000
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Server AMQP Version: 414d515000010000 vs 414d515000010000
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Transitioning from HDR_SENT to HDR_EXCH due to validVersion
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Transitioning from HDR_EXCH to OPEN_SENT due to sendOpen
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Rx: 0000004702000000005310c03a0aa12436386237366637633132633934373763626535393330393437646365653039325f473335407000010000601387700003a9804040404040
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Transitioning from OPEN_SENT to OPENED due to openReceived
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Connected with params { maxFrameSize=65536, channelMax=4999, idleTimeout=120000 }
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Setting heartbeat check timeout to 15000
Fri, 21 Aug 2015 09:29:00 GMT amqp10-client Connected
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Session Transitioning from UNMAPPED to BEGIN_SENT due to sendBegin
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Connection Rx: 0000001e02000000005311c0110860000152015264526452ff4040c10100
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Session Processing frame BeginFrame: {"frameType":0,"channel":0,"remoteChannel":1,"nextOutgoingId":1,"incomingWindow":100,"outgoingWindow":100,"handleMax":255,"offeredCapabilities":null,"desiredCapabilities":null,"properties":{}}
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Session Transitioning from BEGIN_SENT to MAPPED due to beginReceived
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Session On BEGIN_RCVD, setting params to (1,100,100,255)
Fri, 21 Aug 2015 09:29:00 GMT amqp10-client Mapped
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Link Transitioning from DETACHED to ATTACHING due to sendAttach
Fri, 21 Aug 2015 09:29:00 GMT amqp10-Link Tx attach CH=1, Handle=0
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Connection Rx: 0000003402000000005312c0270ea10b712d696e2d6c6f675f525843425001500040404040438000000000000037104040c10100
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Session Processing frame AttachFrame: {"frameType":0,"channel":0,"name":"q-in-log_RX","handle":0,"role":false,"senderSettleMode":1,"receiverSettleMode":0,"source":null,"target":null,"unsettled":null,"incompleteUnsettled":null,"initialDeliveryCount":0,"maxMessageSize":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,55,16]},"offset":0},"offeredCapabilities":null,"desiredCapabilities":null,"properties":{}}
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Transitioning from ATTACHING to ATTACHED due to attachReceived
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Rx attach CH=[1=>0], Handle=[0=>0]
Fri, 21 Aug 2015 09:30:00 GMT amqp10-client Receiver link q-in-log_RX attached
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Connection Rx: 0000015e02000000005316d00000014e00000003434100531dd00000014000000003a315636f6d2e6d6963726f736f66743a74696d656f7574b10000011f5468652072657175657374206861732074696d6564206f75742061667465722030303a30303a3030206d696c6c697365636f6e64732e20546865207375636365737366756c20636f6d706c6574696f6e206f662074686520726571756573742063616e6e6f742062652064657465726d696e65642e204164646974696f6e616c20717565726965732073686f756c64206265206d61646520746f2064657465726d696e652077686574686572206f72206e6f7420746865206f7065726174696f6e20686173207375636365656465642e20547261636b696e6749643a36386237366637633132633934373763626535393330393437646365653039325f4733352c54696d655374616d703a382f32312f3230313520393a33303a303020414d40
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Session Processing frame DetachFrame: {"frameType":0,"channel":0,"handle":0,"closed":true,"error":{"descriptor":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,0,29]},"offset":0},"condition":{"contents":"com.microsoft:timeout"},"description":"The request has timed out after 00:00:00 milliseconds. The successful completion of the request cannot be determined. Additional queries should be made to determine whether or not the operation has succeeded. TrackingId:68b76f7c12c9477cbe5930947dcee092_G35,TimeStamp:8/21/2015 9:30:00 AM","errorInfo":null}}
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Transitioning from ATTACHED to DETACHING due to detachReceived
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Transitioning from DETACHING to DETACHED due to detached
receive error: The request has timed out after 00:00:00 milliseconds. The successful completion of the request cannot be determined. Additional queries should be made to determine whether or not the operation has succeeded. TrackingId:68b76f7c12c9477cbe5930947dcee092_G35,TimeStamp:8/21/2015 9:30:00 AM
Fri, 21 Aug 2015 09:30:00 GMT amqp10-client Link detached: [object Object]
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Transitioning from DETACHED to ATTACHING due to sendAttach
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Link Tx attach CH=1, Handle=0
Fri, 21 Aug 2015 09:30:00 GMT amqp10-client Link q-in-log_RX detached

**Comment by noodlefrenzy** [comment]
Ugh, this is a terrible error:

```
Fri, 21 Aug 2015 09:30:00 GMT amqp10-Session Processing frame DetachFrame: {"frameType":0,"channel":0,"handle":0,"closed":true,
"error":{"descriptor":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,0,29]},"offset":0},"condition":{"contents":"com.microsoft:timeout"},
"description":"The request has timed out after 00:00:00 milliseconds. The successful completion of the request cannot be determined. Additional queries should be made to determine whether or not the operation has succeeded. 
TrackingId:68b76f7c12c9477cbe5930947dcee092_G35,TimeStamp:8/21/2015 9:30:00 AM","errorInfo":null}}
```

I'm forwarding it on to my contact on the ServiceBus team but it might be a few days before they get back to me.

I've tried connect/send/receive to SB Queues with the current code and it works fine. So that means it's either a transient error on their side (my hope), or an issue with the old client (my fear). I'll grab the old client and run a couple of tests to see if I can repro the issue, but if you could try again and see if you're getting the same error, that'd be helpful!

**Comment by edwardconnolly** [comment]
Many thanks. It’s still the same today though.

**Comment by noodlefrenzy** [comment]
Can you post the code you're using to connect? I'd like to try and reproduce it as closely as I can.

Also, you might try using the latest code from master - we're in the midst of revising for V2 of the client. It's an API change (we've promisified most things), but there are examples.

**Comment by noodlefrenzy** [comment]
Also, if I could get your servicebus service name that would help the folks in the SB team find the error messages on their side. If you don't feel comfortable posting here, perhaps email me (milanz@microsoft.com)?

**Comment by edwardconnolly** [comment]
Well it seems that going away and coming back again after a week seems to fix this particular issue.  Here's the simple source code that I got the error with.

```javascript
var util = require('util'),
    AMQPClient = require('amqp10'),
    SERVICE_BUS_NAMESPACE = process.env.SERVICE_BUS_NAMESPACE,
    SERVICE_BUS_KEY = process.env.SERVICE_BUS_KEY,
    SERVICE_BUS_KEY_NAME = process.env.SERVICE_BUS_KEY_NAME,
    SOURCE_NAME = process.env.SOURCE_NAME;
 //   TARGET_NAME = process.env.TARGET_NAME;

function createClient(policy, entityName, connectCallback) {
    var format = 'amqps://%s:%s@%s.servicebus.windows.net/%s',
        url = util.format(format, SERVICE_BUS_KEY_NAME, SERVICE_BUS_KEY, SERVICE_BUS_NAMESPACE, entityName);
    return new AMQPClient(policy, url, connectCallback);
}

createClient(AMQPClient.policies.ServiceBusQueuePolicy, SOURCE_NAME, function sourceConnected(err, sourceClient) {
    if (err) {
        return console.error(err);
    }
    console.log('receiving');
    sourceClient.receive(function receiveCallback(err, payload, annotations) {
        if (err) {
            return console.error('receive error: ' + err);
        }
        console.log('receive payload: ' + JSON.stringify(payload));
        console.log('receive annotations: ' + JSON.stringify(annotations));
    });
});
```

Guess you can close this off. Thanks!

**Comment by mbroadst** [comment]
@edwardconnolly glad to hear it. In case you're interested, we're working hard on releasing an updated version of the library (v2.0.0) that's currently in master. There are examples in the `test` and `examples` folders on how to use the library
