### ISSUE TITLE
Error in retrieving Binary data using Event hub AMQP reciever

### ISSUE THREAD

**Issue by cjpraful** [noodlefrenzy/node-amqp10#174]
I am trying to receive message from event hub using nodejs + amqp. I could observe that the binary data higher than 7f was shown as ef bf bd. I had used Buffer in nodejs. I tried simple_event_hub.js code and modified as shown below to retrieve the binary data.
Could you please check if its a known issue or suggest me workaround for the same. 

var messageHandler = function (myIdx, msg) {
    console.log('Recv(' + myIdx + '): ');
    var data = new Buffer(msg.body)
    console.log(data)

Sent data    :     33 01 00 00 15 00 31 00 32 00 31 00 00 00 A0 10
Received data: 33  01 00 00 15 00 31 00 32 00 31 00 00 00 ef bf bd 10

**Comment by kiran-geon** [comment]
Basically AMQP10 is replacing non-unocode characters in the received binary stream with error characters. Is it possible to force AMQP to treat the data as raw binary?

**Comment by mbroadst** [comment]
@cjpraful @kiran-geon hey, sorry I was waiting for @noodlefrenzy to pick this one up as he's on top of our SB/EH support. I'll see if I can't put together a unit test with the data provided above and track down the issue.

**Comment by mbroadst** [comment]
@cjpraful could you prove me with the actual string values (or even better just the script itself) used to send the data? I've written a few tests using the raw buffers you posted above and they seem to work, I'm wondering if maybe there's a conversion we're doing incorrectly.

**Comment by noodlefrenzy** [comment]
Hey, sorry @cjpraful @kiran-geon @mbroadst - I'm on holiday so less responsive than usual. @mbroadst could it be the encoder/decoder in the service-bus policy? @cjpraful what client is sending the messages? I was unclear from your initial comment whether the sender was our code or just the receiver. If you're planning on sending/receiving just binary data, you could try overriding the policy to avoid the encode/decode logic since you shouldn't need it:

```
var client = new AMQPClient(Policy.merge({
  senderLink: {
    encoder: function(body) { return body; }
  },
  receiverLink: {
    decoder: function(body) { return body; } 
  }
}, Policy.EventHub));
```

(NOTE: I haven't actually tried this - just going off of memory, so apologies if there is a syntax error.)

**Comment by mbroadst** [comment]
@noodlefrenzy yep sounds like an issue with the encoder indeed! If I'm not mistaken we can actually get rid of that specialization in the policy?

**Comment by noodlefrenzy** [comment]
I don't _think_ we can because the C# client encodes the data as a Data block containing a UTF8 binary stream of the JSON-encoded serialization of your object (and expects the same as payload), so our encoder/decoder is built around making that happen so the two can seamlessly interoperate.

**Comment by cjpraful** [comment]
@noodlefrenzy  @mbroadst @kiran-geon  thanks a lot for the inputs.
I tried overriding the policy to avoid the encode/decode logic as @noodlefrenzy  mentioned , I was able to receive raw data as expected.
I was sending data via azure web app to eventhub.

**Comment by mbroadst** [comment]
@cjpraful glad to know it's working!  I'm going to close this, but feel free to open it back up if you run into a related issue.
