### ISSUE TITLE
Get connection failed information

### ISSUE THREAD

**Issue by wmmihaa** [noodlefrenzy/node-amqp10#175]
I running the application from a location where I think the FW is stopping me from reaching sb. When enabling debug the output says:

amqp10:client connection error:  +21s { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

Q1: Is there a way to handle timeouts?
Q2: Is there a prefered fallback. I was thinking of falling back to use the REST API if it doesn't work with  amqp.

Cheers

**Comment by mbroadst** [comment]
Hey,

* what exactly do you mean by "handle timeouts"? The library _should_ be falling into reconnect mode at that point with an exponential backoff, continuing to try again and again (by default the policy indicates it should retry forever). If that's not happening then this sounds like a bug.

 * I think the _only_ fallback is probably the REST api, but @noodlefrenzy would have more to say on this subject.

**Comment by wmmihaa** [comment]
After a closer look I found the reconnect.forver set to true on the Policy.ServiceBusTopic. Setting it to false solved the problem:
var policy = Policy.ServiceBusTopic;
policy.reconnect.forever = false;
policy.reconnect.retries = 2;
var client = new AMQPClient(policy);

Thanks for the help.
Cheers

**Comment by mbroadst** [comment]
@wmmihaa ah yes, that was introduced generally for my case where I have a long-lasting client to my amqp broker. We should document this as a tunable value for people who might want to use this as part of a script (and therefore actually timeout instead of trying to reconnect infinitely).
