### ISSUE TITLE
Receiver link "modify" method causing exception

### ISSUE THREAD

**Issue by davidlenthall** [noodlefrenzy/node-amqp10#176]
The "modify" method causes an "undefined is not a function" exception, as the Modified delivery state sets the ForcedType of the boolean values to "bool". When the codec is then looking for an encoder for for these values it fails as there are none in Types for "bool", changing the ForcedType to "Boolean" fixes this issue:

```
Modified.prototype.getValue = function() {
  var self = this;
  return [
    new ForcedType('boolean', self.deliveryFailed),
    new ForcedType('boolean', self.undeliverableHere),
    new AMQPFields(self.messageAnnotations)
  ];
};
```

**Comment by mbroadst** [comment]
thanks for the bug report, nice catch!
