### ISSUE TITLE
文档描述的例子有问题

### ISSUE THREAD

**Issue by kolonse** [noodlefrenzy/node-amqp10#180]
```
var AMQPClient = require('amqp10').Client,
    Promise = require('bluebird');

var client = new AMQPClient(); // Uses PolicyBase default policy
client.connect('amqp://localhost')
  .then(function() {
    return Promise.all([
      client.createReceiver('amq.topic'),
      client.createSender('amq.topic')
    ]);
  })
  .spread(function(receiver, sender) {
    receiver.on('errorReceived', function(err) { // check for errors });
    receiver.on('message', function(message) {
      console.log('Rx message: ', message.body);
    });

    return sender.send({ key: "Value" });
  })}) /// 这里少了 })
  .catch(function(err) {
    console.log("error: ", err);
  });
```

**Comment by mbroadst** [comment]
@kolonse Hi, unfortunately there are only two of us working on this project and neither of us speaks Chinese. Google translate seems to be failing me as well here, can you try rephrasing in English?

**Comment by kolonse** [comment]
OK! I mean the case of document have a little error. When I use to my project,but cannot run. 
This is problem:

 return sender.send({ key: "Value" });
  }) /// here leak })

Are you understand?  My English is poll, very sorry!

**Comment by mbroadst** [comment]
@kolonse it's okay, your english is much better than my chinese :smile:

Yes, it seems in the code above that you included an extra `})` on L19 that would prevent the code from running with a parse error. Is that what you're referring to? I don't see that same mistake in the docs (though I'm going to clean up some of the neglected examples now), can you point me to the bad documentation if it exists?

**Comment by kolonse** [comment]
@mbroadst 
I'm sorry,I know the question. Because this code on L13 have // mark,so }) of L13 is gray in my JetBrains project! So I think the code leak }) mark
I do not notice it! 
Please receive my knees and very thanks!

**Comment by mbroadst** [comment]
@kolonse glad you figured it out :smile:
