### ISSUE TITLE
Add support for sending multi-frame messages

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#182]
We don't currently support multi-transfer payloads, so messages that cause us to exceed the max-frame parameter will still be sent, and will cause the other side to abort. We should ideally alter our code to support multi-frame messages, but in the interim we should fail the send request with an appropriate error before attempting to send.

**Comment by noodlefrenzy** [comment]
The current plan is to alter `SenderLink._sendMessage` to encode the `message`, determine the size of the resulting payload, and split across multiple `Transfer` frames as appropriate.

**Comment by mbroadst** [comment]
implemented in #186
