### ISSUE TITLE
question: how does amqp10 handle proxy?  

### ISSUE THREAD

**Issue by NNM11** [noodlefrenzy/node-amqp10#191]
Hi,

Could someone please explain how the amqp10 handled the proxy situation for apps using amq10 running behind a firewall?

I am interested in any additional proxy configuration needed for amqp10 to work.  Or if it handled automatically and transparent for the app.

Thanks,

**Comment by noodlefrenzy** [comment]
Hey, sorry for the slow response. We haven't implemented any sort of proxying functionality for our client - it's a strict AMQP 1.0 client, speaking on 5672/5671 (non-secure/secure).

I'm assuming you mean tunneling to your AMQP server over HTTP/HTTPS standard 80/443 ports, yes? I came at this library initially to use with Azure Service Bus, which doesn't support HTTPS proxying, and my colleague on the library doesn't need it for his clients, so we've never looked into it.

All that said, we're relying on standard Node.js-based TCP/SSL semantics for network connections, so if it's a relatively simple matter of setting up an HTTPS-based connection and then driving AMQP binary traffic over it, it should be possible. I'll mark this as an enhancement request and take a look at what would be required.
