### ISSUE TITLE
Error when AMQPClient tries to reconnect in Node

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#201]
https://github.com/Azure/azure-iot-sdks/issues/249

Seen in Azure IoT's use:

```
TypeError: self._reconnect is not a function
    at AMQPClient._attemptReconnection (C:\Source\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\amqp_client.js:330:15)
    at null._onTimeout (C:\Source\node_modules\azure-iot-device-amqp\node_modules\azure-iot-amqp-base\node_modules\amqp10\lib\amqp_client.js:136:21)
  at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by noodlefrenzy** [comment]
Further relevant conversation from the associated iot bug:

> It happens after i leave the code sending messages for about an hour

> Alright, if it's after an hour it's probably because the SAS token has expired. currently the only way to regenerate it is to create a new client, but we do have that captured in our backlog and shall come up with a solution very soon

We should probably not just die a terrible death like that. I'll see if I can't repro.

**Comment by mbroadst** [comment]
likely culprits:
 * https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/amqp_client.js#L283
 * https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/amqp_client.js#L317

**Comment by mbroadst** [comment]
man how many issues do we have open for this bug :smile: 

fixed with https://github.com/noodlefrenzy/node-amqp10/commit/8eeeb5bfecc9f5fddbf16fea22d0f97eb1533dca
