### ISSUE TITLE
Selector management.

### ISSUE THREAD

**Issue by Parsiphal** [noodlefrenzy/node-amqp10#205]
I want to use node-amqp10 in order to create a receiver/sender to a queue/topic deployed on Wildfly.
I have succesfull established the bi-directional communication but now i have to manage the concept of selector jms.

In what way i must manage this requirement with your library?

Thanks all

**Comment by noodlefrenzy** [comment]
Hey @Parsiphal,

I haven't used the library with JMS, but if you take a look at [examples/simple_eventhub_test](https://github.com/noodlefrenzy/node-amqp10/blob/master/examples/simple_eventhub_test.js) you can see me doing something similar (a filter for Event Hubs).

I believe the JMS selector needs to go in the filter while attaching, so it should be similar to the code in that example.  The important pieces are:

```
  filterOption = {
    attach: { source: { filter: {
      'apache.org:selector-filter:string': translator(
        ['described', ['symbol', 'apache.org:selector-filter:string'], ['string', "amqp.annotation.x-opt-offset > '" + filterOffset + "'"]])
    } } }
  };

...

client.createReceiver(curRcvAddr, filterOption)
```

**Comment by Parsiphal** [comment]
Seems to be the solution but where i can find a documentation about the syntax that you have used.

Thanks

**Comment by Parsiphal** [comment]
I have found this http://www.amqp.org/specification/1.0/filters in orther to explain ['symbol', 'apache.org:selector-filter:string']

described seems the translator function creates an object like: 
`{ 'apache.org:selector-filter:string':
   DescribedType {
     descriptor: { contents: 'apache.org:selector-filter:string' },
     value: 'amqp.annotation.x-opt-enqueuedtimeutc > 2000' } }`

I have not found an explanation for this: amqp.annotation....
If i want to create an ApplicationProperties filter what is the syntax?

Thanks.

**Comment by noodlefrenzy** [comment]
http://www.amqp.org/specification/1.0/filters was exactly what I was going to link to. It looks like http://people.apache.org/~rgodfrey/amqp-1.0/apache-filters.html specifies some proposed values (including correlation ID), so it's possible that would work.

The `amqp.annotation` piece is Azure ServiceBus specific (see e.g. https://github.com/Azure/amqpnetlite/wiki/Azure%20Service%20Bus%20Event%20Hubs), but that's my only experience using these filters and I was assuming Wildfly would do something similar.

**Comment by mbroadst** [comment]
@Parsiphal ping. Can we close this issue?

**Comment by mbroadst** [comment]
closed due to lack of information, will reopen if that comes in
