### ISSUE TITLE
Consider throwing in ReceiverLink.settle() in case of bad message

### ISSUE THREAD

**Issue by pierreca** [noodlefrenzy/node-amqp10#206]
In [receiver_link.js line 94](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/receiver_link.js#L94)
if the message passed has anything wrong with it, u.DispositionRange() will fail. at this point instead of ignoring the invalid range, consider throwing an exception (IMHO it's a programmer error, no need for an error callback).

**Comment by mbroadst** [comment]
@pierreca I'm actually working on a huge types refactoring in [this branch](https://github.com/noodlefrenzy/node-amqp10/tree/types-refactor), which will throw errors when we're missing mandatory fields in a composite type (amongst many many other improvements).

**Comment by mbroadst** [comment]
@pierreca my work has now been merged into v3, I believe we can close this issue but I'll wait for your response before doing so

**Comment by pierreca** [comment]
your call. we haven't moved to v3 yet, but I don't think we're impacted by this anymore. I'm OK to close the issue.

**Comment by mbroadst** [comment]
Okay sounds good, thanks!
