### ISSUE TITLE
Azure Service Bus receive body type string

### ISSUE THREAD

**Issue by gjr-qm** [noodlefrenzy/node-amqp10#207]
An external system sends a message (xml) with body type string from a .NET application (because they had some encoding problems when sending the message as stream). When we receive the message we get:

`@\u0006string\b3http://schemas.microsoft.com/2003/10/Serialization/�9<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<foo><bar/></foo>`

Do i have to deserialize the message body myself or is there some standard functionality from this (couldn't find a clue in the api docs or sourcecode)?
If so, can i detect the body type?

**Comment by noodlefrenzy** [comment]
Hey, sorry for the delay. If you're using the Service Bus policy, then it should be using the following decoder when messages come in: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/service_bus_policy.js#L28

This should automagically handle if it's sent as a proper string, but what it looks like is happening is it's being sent as a buffer with an embedded .NET-serialized string object. We can't handle that very well.

What sort of issues were they having with sending as a stream? Were they having issues with `BrokeredMessage(Stream)` construction or something?

**Comment by gjr-qm** [comment]
Thank you for your answer. The guys from the external system (BizTalk, Navision) experienced some encoding problems constructing a proper UTF-8 encoded stream with xml content in it.

I think, with the help of your answer, they are on the right track now. Thanks again.

Great library btw! I had it up and running without problems in a very short time.

**Comment by noodlefrenzy** [comment]
Fantastic! Closing this, let me know if you run across other issues. Also, you can always merge the service bus policy with your own that just declares its own custom encoder/decoder if you need to add your own logic there.
