### ISSUE TITLE
a little question of latest version 3.1.1 

### ISSUE THREAD

**Issue by kolonse** [noodlefrenzy/node-amqp10#229]
hello~!
I use the version 3.1.1 and find a question. my client connect to apache activemq server, and  let it idle above 30s. my server have a error :
**INFO   | jvm 4    | 2016/03/30 14:53:31 |  WARN | Transport Connection to: tcp://127.0.0.1:49561 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for to long
INFO   | jvm 4    | 2016/03/30 14:53:31 |  WARN | Transport Connection to: tcp://127.0.0.1:49562 failed: org.apache.activemq.transport.InactivityIOException: Channel was inactive for to long**

but i use the version 2.1.2 not happen! 
so ,can you help me resolve this question?

**Comment by mbroadst** [comment]
@kolonse can you show us some code examples here? Are you making sure to use the ActiveMQ policy? There was a massive overhaul of the protocol internals in 3.x which lead to a 50% improvement in performance, but may have also resulted in bringing to light some bugs we had previously missed. If you're currently experiencing one of those I'd like to fix it quickly :)

**Comment by kolonse** [comment]
I think this is a config of new version, I will learning the docment and resolve it~!  Now my project use old version. when i know how to use new version, i upgrade my version. Thanks for you!

**Comment by kolonse** [comment]
My code is here:
`var AMQPClient = require("amqp10").Client;
var moment = require("moment");
console.debug = console.trace;
var MsgSenderClient = function(opt){
    opt = opt || {
        reconnect:{
            forever:true,
            strategy: 'fibonacci',
            retries:10
        }
    } ;
    this.opt = opt ;
    this.logger = opt.logger || console ;
    this.uri = opt.uri || "amqp://localhost" ;
    this.name = opt.name || "amq.msg.queue" ;
    this.client = new AMQPClient();
    this.sender = null ;
}

MsgSenderClient.prototype.run = function(callback){
    var self = this ;
    callback = callback || function(err){
        if( err ) console.log(err)
    } ;
    self.client.connect(this.uri)
        .then(function(){
            // 创建接收者
            return self.client.createSender(self.name);
        })
        .then(function(sender){
            self.sender = sender ;
            callback(null);
        })
        .catch(function(err){
            // 出现错误那么要通知用户层
            callback(err);
        });
}

MsgSenderClient.prototype.send = function(message,callback){
    callback = callback || function(err){
        if( err ) console.log(err)
    } ;
    var self = this ;
    if(self.sender){
        self.sender.send(message)
            .then(function(){
                callback(null);
            })
            .catch(function(err){
                callback(err)
            });
    }else{
        callback(new Error("当前发送器未创建成功"));
    }
}

MsgSenderClient.prototype.sendMsg = function(event,data,callback){
    data.createdAt = moment(new Date()).format("YYYY-MM-DD HH:mm:ss") ;
    var message = {
        event:event,
        data:data
    }
    this.send(message,callback);
}

module.exports = function(opt){
    var ret = new MsgSenderClient(opt);
    //ret.run();
    return ret ;
}`

**Comment by mbroadst** [comment]
@kolonse thanks for your bug report, I found the error (a typo: `idleTimeOut` vs `idleTimeout` *sigh*) and committed a fix (as well as a unit test this time!) published as v3.1.2. Please do an `npm install` to update, and the problem should be resolved!

**Comment by kolonse** [comment]
@mbroadst thanks for you! i'd like to use your open source code. last time, i find other bug,and you fix it very fast. this code be used my project a long time,thanks very much!
