### ISSUE TITLE
Add a History.md file

### ISSUE THREAD

**Issue by MorganLindqvist** [noodlefrenzy/node-amqp10#231]
Hi,

I would like more information about what changes that are included in a new release. Would it be possible to start a History.md file that describes that changes since the last release.

As a user you then know what to pay extra focus on when starting to use the new version.

/Morgan

**Comment by mbroadst** [comment]
@MorganLindqvist sounds like a great idea, in fact I believe since we've been pretty good about commit formatting I might be able to just get away with using [conventional-changelog](https://www.npmjs.com/package/conventional-changelog). I'll look into it this afternoon.

**Comment by mbroadst** [comment]
@MorganLindqvist committed: https://github.com/noodlefrenzy/node-amqp10/blob/master/CHANGELOG.md
