### ISSUE TITLE
How to use SSL client certificates

### ISSUE THREAD

**Issue by MorganLindqvist** [noodlefrenzy/node-amqp10#232]
Hi,

Is there an example somewhere which shows how I could use SSL client certificates to connect to a AMQP server?

Best Regards,
Morgan

**Comment by mbroadst** [comment]
@MorganLindqvist we don't have any examples out of the box, but to give you a quick overview:

SSL information is passed directly to node's tls module from the policy in the form:
```
policy = {
  connect: {
    sslOptions: {
       // your options here
    }
  }
}
```

The options themselves are documented here: https://nodejs.org/api/tls.html#tls_tls_connect_options_callback.

HTH

**Comment by MorganLindqvist** [comment]
Hi @mbroadst 

I ended up reading all the source code and eventually found how it should be done. It is however not as you describe above. sslOptions is a JSON struct with the following parameters { keyFile:: 'path and file name', certFile: 'path and file name', caFile: 'path and file name', rejectUnauthorized: booleanValue }

Of these four parameters only the last one exists in the "real" sslOption struct, the first three only exists in amqp10::sslOptions. The "real" sslOptions have a lot of other parameters but these are hidden by you implementation.

The code for this can be found here https://github.com/noodlefrenzy/node-amqp10/blob/f3fd9f639d5d3fed3f86e33a20266324f1f35789/lib/connection.js

**Comment by mbroadst** [comment]
@MorganLindqvist ah indeed you are correct, my apologies! I think I was just wishfully thinking, considering we _should_ just pass those options wholesale rather than pick out a small amount of supported options. I'll make a note to support all the options.

**Comment by gbeister** [comment]
Hi,
has been a while this topic has been touched, but is there an official and documented way of how to use amqp10 via amqps by involving a certificate-file to use?

The way I'm trying to connect currently is as follows:
`var client = new AMQPClient(Policy.merge({
	connect: {
		sslOptions: {
			caFile: <path to my *.pem file>
		}
	}
},Policy.DefaultPolicy));

client.connect(<url to amqp endpoint>).then(function() {
...
}
`
when doing so, I get the following error:
buffer.js:183
    throw new TypeError(kFromErrorMsg);
    ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at BufferBuilder.appendString (<my project path>\node_modules\buffer-builder\buffer-builder.js:73:28)
    at SaslPlain.getInitFrame (<my project path>\node_modules\amqp10\lib\sasl\sasl_plain.js:13:7)
    at Sasl._processFrame (<my project path>\node_modules\amqp10\lib\sasl\sasl.js:72:18)
    at Connection._processFrameEH (<my project path>\node_modules\amqp10\lib\sasl\sasl.js:37:49)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Connection._receiveAny (<my project path>\node_modules\amqp10\lib\connection.js:427:12)
    at Connection._receiveData (<my project path>\node_modules\amqp10\lib\connection.js:358:8)
    at TlsTransport.<anonymous> (<my project path>\node_modules\amqp10\lib\connection.js:516:38)
    at emitOne (events.js:115:13)
    at TlsTransport.emit (events.js:210:7)
    at TLSSocket.<anonymous> (<my project path>\node_modules\amqp10\lib\transport\tls_transport.js:29:49)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)

The debug-output till this point is as follows:
amqp10:client connecting to: amqps://<my amqp endpoint> +0ms
  amqp10:transport:tls Connecting to <my amqp endpoint> via TLS +20ms
  amqp10:connection stateChange: DISCONNECTED => START , reason: connect +2ms
  amqp10:connection Sending Header 414d515003010000 +101ms
  amqp10:connection stateChange: START => IN_SASL , reason: connected +4ms
  amqp10:trace Rx: 414d515003010000 +39ms
  amqp10:sasl Server SASL Version: 414d515003010000 vs 414d515003010000 +6ms
  amqp10:trace Rx: 0000005802010000005340d00000004800000001f00000003f00000004b300000005504c41494e0000000b534352414d2d5348412d310000000d534352414d2d5348412d3235360000000d534352414d2d5348412d353132 +5ms
  amqp10:framing <= @sasl-mechanisms(64) [saslServerMechanisms=[ 'PLAIN', 'SCRAM-SHA-1', 'SCRAM-SHA-256', 'SCRAM-SHA-512' ]] +11ms
  amqp10:trace raw: [005340d00000004800000001f00000003f00000004b300000005504c41494e0000000b534352414d2d5348412d310000000d534352414d2d5348412d3235360000000d534352414d2d5348412d353132] +8ms

Any help is highly appreciated.

Thanks a lot!
