### ISSUE TITLE
question about client.createsender

### ISSUE THREAD

**Issue by geoffreysamper** [noodlefrenzy/node-amqp10#240]
I want to test some code against azure event hub pretty simple process a forever loop that keep sending messages. On every message I call the createsender method of the amqp client. After sending 255 message i received  **AmqpOverCapacityError: Out of available handles (Max = 255)**. So what i instead of creating a sender on for each message I reused the sender.
**BEFORE**
```javascript
var counter = 0; 
client.connect(uri)
  .then(function () {
    "use strict"
    async.forever(function(next){
      //sender created inside the loop
     let senderPromise = client.createSender(sendAddr).then(function (sender) {
      let message = { DataString: 'From Node', DataValue: msgVal };
      let options = { annotations: { 'x-opt-partition-key': 'pk' + msgVal } };
      sender.send(message, options).then(function (state) {
        // this can be used to optionally track the disposition of the sent message
        console.log('state: ', counter);
        counter ++
        next();
      });
    })
    })
  })
```

**AFTER**

```javascript
var counter = 0; 
client.connect(uri)
  .then(function () {
    "use strict"
    //sender created outside the loop
     let senderPromise = client.createSender(sendAddr).then(function (sender) {
    async.forever(function(next){
      let message = { DataString: 'From Node', DataValue: msgVal };
      let options = { annotations: { 'x-opt-partition-key': 'pk' + msgVal } };
      sender.send(message, options).then(function (state) {
        // this can be used to optionally track the disposition of the sent message
        console.log('state: ', counter);
        counter ++
        next();
      });
    })
    })
  })
```

The question is can we use the same sender to send multiple messages or should we always create a **new** sender to send a message. The scenario where I used is in a web api using express

Thx

**Comment by mbroadst** [comment]
You should absolutely use the same sender for multiple messages. Here's a cleaned up example:

```
'use strict';

let counter = 0;
client.connect(uri)
  .then(() => client.createSender(sendAddr))
  .then(sender => {
    async.forever(next => {
      let message = { DataString: 'From Node', DataValue: msgVal };
      let options = { annotations: { 'x-opt-partition-key': 'pk' + msgVal } };

      return sender.send(message, options)
        .then(state => {
          console.log('state: ', counter);
          counter++;
          next();
        });
    });
  });
```

The issue you were running into in the `before` case is that you never actually closed/detached the sender links you were creating, and therefore ran out of handles for the connection.

**Comment by geoffreysamper** [comment]
How can i close or detach the sender form the connection? I can't find any method on the sender object to do that

**Comment by mbroadst** [comment]
https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/link.js#L110

**Comment by mbroadst** [comment]
Furthermore, if you use [this](https://github.com/mbroadst/amqp10-link-cache) module, you can maintain a cache for links which will automatically expire unused links after a defined TTL

**Comment by geoffreysamper** [comment]
Ok thanks for the help
