### ISSUE TITLE
Apache ActiveMQ create topic

### ISSUE THREAD

**Issue by grill2010** [noodlefrenzy/node-amqp10#241]
Hi,

I could not create any topic on Apache ActiveMQ. Below you can find my code:

```
var client = new AMQPClient();
var brokerUrl = "amqp://localhost:5672/?clientid=ocm_server";
log.info("Broker url: " + brokerUrl);
client.connect(brokerUrl).then(function () {
    log.info("Established connection to broker");
    return Promise.all([
        client.createSender("topic://CallData"),
        client.createReceiver("topic://CallData")
      ]).spread(amqpHandler);
    });
```

Did I do something wrong? The weird thing is that when I look on the ActiveMQ Webinterface the only thing which was created is a queue element with the name topic:
Many thanks for your help.

**Comment by mbroadst** [comment]
@grill2010 hmm that looks like it should work. We don't actively test ActiveMQ, but have in the past.. could you possibly provide the debug logs for this attempt? (add the following environment variable: `DEBUG=amqp*`)

**Comment by grill2010** [comment]
Hi, many thanks for your quick response. I figured out the problem. It seems that I have to pass the ActiveMQ standard policy to the AMQPClient.

```
var activeMQPolicy = require("amqp10").Policy;
var client = new AMQPClient(activeMQPolicy.ActiveMQ);
```

It works as expected now.

best wishes

**Comment by mbroadst** [comment]
👍
