### ISSUE TITLE
Unable to choose AMQP encoding for Buffer or Array types

### ISSUE THREAD

**Issue by dnwe** [noodlefrenzy/node-amqp10#255]
Currently the `encodeMessage` function in `lib/types/message.js` makes the following encoding decisions based upon the type of the `message.body`
```js
if (message.body instanceof Buffer) {
  codec.encode(new DescribedType(0x75, message.body), buffer);  // Data
} else if (Array.isArray(message.body)) {
  codec.encode(new DescribedType(0x76, message.body), buffer);  // AMQPSequence
} else {
  codec.encode(new DescribedType(0x77, message.body), buffer);  // AMQPValue
}
```

However, it is equally valid to take Buffer data and put it into a Binary type within an AMQPValue, or to take Array data and put it into an Array/List in an AMQPValue. Whilst the `codec.encode(..)` supports both of these, there doesn't appear to be a policy-based way of opting into the behaviour of always stuffing things into an AMQPValue.

**Comment by mbroadst** [comment]
related: https://github.com/noodlefrenzy/node-amqp10/issues/97

**Comment by dnwe** [comment]
Fixed.
