### ISSUE TITLE
Unablt to connect, stuck on "Transitioning from START to IN_SASL due to connected"

### ISSUE THREAD

**Issue by tirithen** [noodlefrenzy/node-amqp10#259]
I can't get to any of the callbacks on the connection, neither with correct/invalid authentication credentials. It gets stuck on the state "Transitioning from START to IN_SASL due to connected". I have auto reconnect setup so the same message is printed over and over. Why are the this.client.connect call neither resolving as success nor failure? Is there some event somewhere that I should be listening to instead?

(Trying to connect to an instance of ActiveMQ version 5.13.2)

```
DEBUG=amqp* AMQP_PORT=61613 AMQP_USER=consumer AMQP_PASSWORD=password node .   
  amqp10:client connecting to: amqp://consumer:password@localhost:61613 +0ms
  amqp10:transport:net Connecting to localhost:61613 via straight-up sockets +6ms
  amqp10:connection Transitioning from DISCONNECTED to START due to connect +3ms
Connecting using amqp://consumer:password@localhost:61613
  amqp10:connection Sending Header 414d515003010000 +2ms
  amqp10:connection Transitioning from START to IN_SASL due to connected +0ms

```

```
const AMQP = require('amqp10');

const AMQP_HOST = process.env.AMQP_HOST || 'localhost';
const AMQP_PORT = process.env.AMQP_PORT || 5672;
const AMQP_USER = process.env.AMQP_USER;
const AMQP_PASSWORD = process.env.AMQP_PASSWORD;

let uri = '';
if (AMQP_USER) {
  uri = `amqp://${AMQP_USER}:${AMQP_PASSWORD}@${AMQP_HOST}:${AMQP_PORT}`;
} else {
  uri = `amqp://${AMQP_HOST}:${AMQP_PORT}`;
}

this.client = new AMQP.Client(AMQP.Policy.ActiveMQ);
this.client.connect(uri).then(() => {
  console.log('connected', `amqp://${AMQP_HOST}`);
  this.client.createReciever('log').then((reciever) => {
    console.log('reciever created');
    reciever.on('message', (message) => {
      const level = message.level === 'warning' ? 'warn' : message.level;

      if (console[level] instanceof Function) {
        if (message.package) {
          console[level](
            (new Date(message.date).toISOString()),
            message.package.name,
            message.package.version,
            message.level,
            message.data
          );
        } else {
          console[level](
            (new Date(message.date).toISOString()),
            message.level,
            message.data
          );
        }
      }
    });
  }, (error) => {
    // Is this useful or are ErrorRecieved event listner enough??
    console.error(error);
    throw new Error('Unable to create a reciever for the amqp service, exiting');
  });
}, (error) => {
  // Is this useful or are ErrorRecieved event listner enough??
  console.error(error);
  throw new Error('Unable to connect to the amqp service, exiting');
});

this.client.on(AMQP.Client.ErrorReceived, error => console.error(error));

console.log(`Connecting using ${uri}`);

```

**Comment by mbroadst** [comment]
@tirithen do the logs stop there? There's no further data sent?

**Comment by tirithen** [comment]
Yes, they stop there

**Comment by mbroadst** [comment]
That looks like the amqp server isn't responding to anything on that port, are you sure you have an AMQP 1.0 listener on that port? (I noticed in the log you are connecting to port 61613 but default to the expected 5672 in your code snippet)

**Comment by mbroadst** [comment]
Oh. Port 61613 is for the STOMP protocol, we do not support that with this library.

**Comment by tirithen** [comment]
I thought so, using docker image from https://hub.docker.com/r/webcenter/activemq/

**Comment by tirithen** [comment]
Ah, guess I need to find out more about that docker image as well. Would still be great with a failed to connect callback somewhere even in that case though. :)

**Comment by mbroadst** [comment]
Well that's exactly it, from our perspective we did not fail. This is like sending ssh commands to a telnet server, at what point do you say this failed to a user? We could theoretically time out on the connection attempt I guess

**Comment by tirithen** [comment]
Okay, yes maybe that makes sense. But what if you have configured the ports in a bad way for example. If nothing is listening I do get an error.

**Comment by tirithen** [comment]
Anyway, it's probably mostly me that is new to this and need to find a docker image with ActiveMQ that works.

**Comment by mbroadst** [comment]
@tirithen let's look at it another way. When you screw up the ports, and we connect and give you an error that's like making a telephone call and getting an "out of service" error from the telephone company - you're right, we propagate that error from the operating system in that case. In your case here, it's like you are a person who speaks english calling what they _think_ is another person who speaks english, but instead getting someone who speaks Mongolian. The connection succeeded, and you say "hello" and then get nothing in return because the Mongolian has no idea what you said. There is no error to be propagated here, you simply have made a mistake from your side. The only thing that could be done is to modify the connect code such that if in <some interval of time> the connection does not succeed, then we could throw a "timeout error".

**Comment by mbroadst** [comment]
WRT your docker image, iirc ActiveMQ comes with support for AMQP 1.0 and STOMP out of the box. You simply need to make sure you enable the AMQP 1.0 backend, and connect on the default port of 5672

**Comment by tirithen** [comment]
:) Okay, it's okay

Yes, realized that now, so enabled port 5672 but instead got some protocol version problem 

Server AMQP Version: 6976654d51000000 vs 414d515000010000

**Comment by tirithen** [comment]
Nevermind now everything works! :D
