### ISSUE TITLE
deliveryTag not exposed on message

### ISSUE THREAD

**Issue by princjef** [noodlefrenzy/node-amqp10#263]
First of all, thanks for all of your work on this library! It makes working with AMQP a breeze.

I am trying to do some AMQP request/response operations on messages that come in on a receiver attached to Service Bus. As part of my request, I need to pass the deliveryTag of the message I want to work with. However, it looks like the deliveryTag is never passed from the transfer frame into the message object.

Would it be possible to pass the deliveryTag through in some way? My workaround right now is just to do another Object.defineProperty() like [_deliveryId](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/receiver_link.js#L154) to pass the Buffer through. However, since my intention is to use it outside of the library, an underscored, non-enumerable property doesn't seem like the right approach.

**Comment by mbroadst** [comment]
@princjef hey, what if we extended the `ReceiverLink` `message` emission to include the original frame? For instance you would have:

```
client.createReceiver('amq.topic')
  .then(receiver, => receiver.on('message', (msg, frame) => ...));
```

**Comment by mbroadst** [comment]
btw doing something with that extra argument is completely opt-in, so this would _not_ break the following:
```
client.createReceiver('amq.topic')
  .then(receiver => receiver.on('message', (msg) => ...));
```

**Comment by princjef** [comment]
@mbroadst I like that approach a lot. It exposes the information only if someone wants it and also future-proofs in case there is other information from the frame that people need down the line.

**Comment by mbroadst** [comment]
@princjef great. Your timing is impeccable, today is my amqp10 day :) I'll put together a PR quickly if you have some time to give it a spin on your side.

**Comment by princjef** [comment]
Yeah definitely! Let me know when you've got something

**Comment by mbroadst** [comment]
Give it a spin on this branch: https://github.com/noodlefrenzy/node-amqp10/tree/emit-transfer-frame.

It should be noted that we don't provide a way for you to _set_ the `deliveryTag` from the `SenderLink` side of the equation - but my interpretation of the spec is that that's the way it should be 😄

**Comment by princjef** [comment]
Works as expected. Nice!

Yeah that seems reasonable. The deliveryTag ends up getting passed in the body of the message I need to send on the other side so no issues there 😄

**Comment by mbroadst** [comment]
added in cd59fecb940dd9462841c08e94c43055712f67c8
