### ISSUE TITLE
amqp10@3.3.0 breaks support for x509 certificates

### ISSUE THREAD

**Issue by pierreca** [noodlefrenzy/node-amqp10#268]
This change: https://github.com/noodlefrenzy/node-amqp10/commit/d0672022f57d979c7645117ccb197fc2f19bc373

uses `deepMerge` but `deepMerge` doesn't support duplicating objects of type `Buffer`, which are used to store certificates and keys in the `sslOptions` field (`Buffer` constructors require arguments, and 
https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/utilities.js#L120 will not pass them).

**Comment by dnwe** [comment]
@mbroadst oops. As this is a breaking regression, should we be pushing out a 3.3.1?
