### ISSUE TITLE
api/README.md seems pretty out-of-date

### ISSUE THREAD

**Issue by dnwe** [noodlefrenzy/node-amqp10#269]
The [api/README.md](/noodlefrenzy/node-amqp10/tree/master/api) hasn't been rebuilt in over a year and is pretty out-of-date since all the types refactoring etc.

I did investigate bumping up [jsdoc2md/jsdoc-to-markdown](/jsdoc2md/jsdoc-to-markdown) version (to avoid a npm install error about deprecated minimatch) and re-building, but it seemed like we have a lot less jsdoc than we used to and so the api/README.md becomes quite small, so I'm not sure what the best thing to do here is?

**Comment by mbroadst** [comment]
@dnwe a good point indeed. The api/README.md traditionally documented _everything_, but I wonder if we should actually just be documenting the user-facing API. What are your thoughts on this?

**Comment by mbroadst** [comment]
@dnwe I'm looking into this today. Do you feel like having documentation generated for every file was useful for you from a user's perspective? It seems to me like maybe our documentation should just be for user-facing API (so like `AmqpClient` and `Policy` basically), but I could be convinced otherwise

**Comment by mbroadst** [comment]
@dnwe https://github.com/noodlefrenzy/node-amqp10/blob/update-docs/DOCUMENTATION.md

That's the work I got through today. It looks like adding this directly to our README would involve an extra build step (generating our README from a handlebars template etc), so I went directly with placing a DOCUMENTATION.md file in the root which can be linked to from the README.md. 

It's definitely incomplete, but more thorough (and hyperlinked) than before. Thoughts?

**Comment by mbroadst** [comment]
@dnwe I've merged in the documentation updates. It's far from complete but I think in a much better place than it was before, also it should be somewhat easier for users to help fill in now (via jsdoc). Documentation is built using `make docs` from the command line in the top level of the repo, and its linked to from the `README.md`
