### ISSUE TITLE
Can't change source link address on `createSender()` or target link address on `createReceiver()`

### ISSUE THREAD

**Issue by princjef** [noodlefrenzy/node-amqp10#277]
I have been trying to implement the request/response pattern in the [AMQP Management working draft](https://www.oasis-open.org/committees/download.php/52425/amqp-man-v1%200-wd08.pdf) on top of node-amqp10.

It works by using a sender/receiver link pair, where the sender sets the `replyTo` property to the address of the receiver so that the response is sent to the correct place. In the spec, the sender sets its `source` address to `null` and the `receiver` sets its `target` address to a unique value that can be used in the `replyTo` field on sent messages. However, in `createSender()` and `createReceiver()`, the source and target, respectively, are set to `'localhost'` and cannot be overridden.

I looked at `parseLinkAddress()` but it only applies to the opposite component of the address, so it doesn't seem like there is any way to override this. To get it working, I moved around the values in the policy merge to allow overriding. This is what it looks like for [`createReceiver()`](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/amqp_client.js#L261):

``` js
  var linkName = u.linkName(address.name, policyOverrides),
      linkPolicy = u.deepMerge({
        attach: {
          name: linkName,
          source: { address: address.name }
        }
      }, policyOverrides, { attach: { target: { address: 'localhost' } } }, this.policy.receiverLink);
```

Any ideas/suggestions?

**Comment by mbroadst** [comment]
@princjef have you checked out the source for [amqp10-rpc](https://github.com/mbroadst/amqp10-rpc) ? I think I'm doing something similar here: https://github.com/mbroadst/amqp10-rpc/blob/master/lib/rpc-client.js#L16. 

You should definitely be able to override any value using the `policyOverrides`, so if we have a problem there (perhaps `deepMerge`/`deepCopy` is striking again!) then we need to resolve that.

**Comment by princjef** [comment]
@mbroadst I think I have the opposite. I need to specify the address for the link that I am creating (a.k.a sender -> source, receiver -> target). I believe dynamic tells the link on the opposite end (sender -> target, receiver -> source) to set its own address.

As for whether it is overridable, it looks like `deepMerge` gives precendence in the opposite order of `Object.assign`, overriding values specified in later arguments with those specified in earlier ones. The current linkPolicy merge for `createReceiver` looks like this:

```js
  var linkName = u.linkName(address.name, policyOverrides),
      linkPolicy = u.deepMerge({
        attach: {
          name: linkName,
          source: { address: address.name },
          target: { address: 'localhost' }
        }
      }, policyOverrides, this.policy.receiverLink);
```

Based on the current order, both the overall policy and the overrides are overridden for the source and target addresses. Even if the precedence is reversed, the base policy will override the policyOverrides. The only way I see to enable this is to reshuffle the arguments or provide some sort of escape hatch function.

**Comment by mbroadst** [comment]
@princjef yeah `deepMerge`/`deepCopy` has been a pretty steady source of issues, I'd like to get rid of them possibly in favor of an `Object.assign` ponyfill or at least making it act more like `Object.assign` in terms of ordering etc (`deepMerge` does constructor-level copying, so its a weird beast with particular requirements unfortunately).  It's also a breaking change, so we'd have to push up the major number - something I was hoping to do if/when we convert the codebase to ES6 (in which case we can just use `Object.assign`). 

I'll take a look at this case in a little bit and see if we can't at least get the overrides working as expected for your case.

**Comment by princjef** [comment]
@mbroadst not sure what kind of change you had in mind, but I added a couple of tests for the way I addressed it and submitted a pull request. I can also modify if you have a better idea of how to address it.

Is there a place where features/changes for 4.x are being tracked? An ES6 codebase would be very welcome, though a large refactor. Just curious if there are any other big changes on the roadmap.

**Comment by mbroadst** [comment]
@princjef I took a stab at refactoring your PR over here: https://github.com/noodlefrenzy/node-amqp10/pull/279. I think this is probably closer to what we want, and should not be a breaking change (like your solution).  Please give it a shot locally and let me know if you have any issues.

As far as features being tracked for 4.x, currently the short answer is: no. We're in the process of moving the project to its own github organization so I can have more control over the issues, milestones, tags, etc. Until then I don't actually have the permissions to set up a spot for discussion. In the meantime I would recommend stopping by our [gitter](https://gitter.im/noodlefrenzy/node-amqp10), and hopefully we can get some milestones put together shortly.

Regarding the ES6 port: I think it's a good idea in general, as it would greatly reduce my maintenance burden (considering I'm working exclusively in ES6 these days), and therefore would probably be worth the effort (probably ~a weekend of work). There is some concern about supporting legacy codebases as the Azure IoT guys still have users on node 0.10.x, @pierreca and I have discussed this briefly and _think_ we can probably do something like push forward with a 4.x with ES6 while backporting critical fixes to the 3.x branch on an as-needed basis. It remains to be seen whether npm will allow us to release in this fashion. Currently this is the only large user-facing refactor I have in mind.

**Comment by princjef** [comment]
@mbroadst I tested it out and everything looks good. Thanks!

Thanks for the info. I'll take a look at gitter. I'm not sure what Babel's compatibility level looks like but you might be able to get it to transpile ES6 into node 0.10 compatible code. You could even potentially keep transpiled and non-transpiled forms in the package, exporting the transpiled form under `'amqp10/legacy'` or something like that.
