### ISSUE TITLE
Using websocket for simple_eventhub_test.js

### ISSUE THREAD

**Issue by albhardy** [noodlefrenzy/node-amqp10#285]
I noticed there's already support for [AMQP over websockets for Azure IoT Hub](https://github.com/noodlefrenzy/node-amqp10/pull/194), however I could not figure out configuration needed to connect to IOT Event Hub-compatible endpoint websocket port 443 in simple_eventhub_test.js (Tried to change the  protocol to `wss` as well as appending `:443`) 

    {
        "SASKeyName":"iothubowner",
        "SASKey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "serviceBusHost":"xxxxxxxxxxxx.servicebus.windows.net",
        "eventHubName":"xxxx-xxxx-xxxx-xxxx-xxxx",
        "partitions":2,
        "protocol":"wss"
    }

How can I make node-amqp10 use Web Socket connection to read data from Azure EventHub?

**Comment by mbroadst** [comment]
You'll need to make sure you are using the websocket transport [module](https://github.com/noodlefrenzy/node-amqp10-transport-ws). So you would basically have at the top of your script:

```
const amqp = require('amqp10');
amqp.use(require('amqp10-transport-ws'));

/* everything else as usual */
```

**Comment by albhardy** [comment]
I tried it but receive no response :(


       'use strict';
        const amqp = require('amqp10'),
            wsTransport = require('amqp10-transport-ws');
        wsTransport.register(amqp.TransportProvider);


        var AMQPClient = amqp.Client;
        var Policy = require('amqp10').Policy;
        var translator = require('amqp10').translator;
        var Promise = require('bluebird');

        var settingsFile = process.argv[2];
        var settings = {};
        if (settingsFile) {
        settings = require('./' + settingsFile);
        } else {
        settings = {
            serviceBusHost: process.env.ServiceBusNamespace,
            eventHubName: process.env.EventHubName,
            partitions: process.env.EventHubPartitionCount,
            SASKeyName: process.env.EventHubKeyName,
            SASKey: process.env.EventHubKey
        };
        }

        if (!settings.serviceBusHost || !settings.eventHubName || !settings.SASKeyName || !settings.SASKey || !settings.partitions) {
        console.warn('Must provide either settings json file or appropriate environment variables.');
        process.exit(1);
        }

        var protocol = settings.protocol || 'amqps';
        var serviceBusHost = settings.serviceBusHost + '.servicebus.windows.net';
        if (settings.serviceBusHost.indexOf(".") !== -1) {
        serviceBusHost = settings.serviceBusHost;
        }
        var sasName = settings.SASKeyName;
        var sasKey = settings.SASKey;
        var eventHubName = settings.eventHubName;

        var uri = protocol + '://' + encodeURIComponent(sasName) + ':' + encodeURIComponent(sasKey) + '@' + serviceBusHost;
        var managementEndpoint = '$management';

        var rxName = 'client-temp-node';
        var rxOptions = { attach: { target: { address: rxName } } };
        var client = new AMQPClient(Policy.EventHub);
        console.log("uri:"+uri)
        client.connect(uri)
        .then(function () {
            return Promise.all([
            client.createReceiver(managementEndpoint, rxOptions),
            client.createSender(managementEndpoint)
            ]);
        })
        .spread(function (receiver, sender) {
            sender.on('errorReceived', function (tx_err) { console.warn('===> TX ERROR: ', tx_err); });
            receiver.on('errorReceived', function (rx_err) { console.warn('===> RX ERROR: ', rx_err); });
            receiver.on('message', function (msg) {
            console.log('Message received: ');
            console.log('Number of partitions: ' + msg.body.partition_count);
            console.log('Partition IDs: ' + msg.body.partition_ids);
            client.disconnect().then(function() {
                console.log('=== Disconnected ===');
                process.exit(0);
            });
            });

            var request = {
            body: 'stub',
            properties: { messageId: 'request1', replyTo: rxName },
            applicationProperties: { operation: 'READ', name: eventHubName, type: 'com.microsoft:eventhub' }
            };
            return sender.send(request).then(function (state) {
            // this can be used to optionally track the disposition of the sent message
            console.log('State: ', state);
            });
        })
        .error(function (e) {
            console.warn('connection error: ', e);
        });


Not sure there's special URI for EventHub WebSocket. In [Azure-IOTHub amqp_ws.js](https://github.com/Azure/azure-iot-sdk-node/blob/master/service/lib/amqp_ws.js), the code specifies `wss://` and `':443/$iothub/websocket'` to connect.

**Comment by mbroadst** [comment]
@albhardy could you try running with debug messages enabled (specify `DEBUG=amqp*` as an environment variable before running your script), and paste the output here?

**Comment by albhardy** [comment]
Following is the output:

        > node amq2.js config.json
        uri:amqps://iothubowner:xxxxxxxxxx%3D@yyyyyyyyyyyyyyy.servicebus.windows.net
          amqp10:client connecting to: amqps://iothubowner:xxxxxxxxxx%3D@yyyyyyyyyyyyyyy.servicebus.windows.net +0ms
          amqp10:transport:tls Connecting to yyyyyyyyyyyyyyy.servicebus.windows.net:5671 via TLS +15ms
          amqp10:connection Transitioning from DISCONNECTED to START due to connect +16ms
          amqp10:connection Error from socket: Error: connect ETIMEDOUT 40.112.185.115:5671 +21s
          amqp10:client connection error:  { Error: connect ETIMEDOUT 40.112.185.115:5671
            at Object.exports._errnoException (util.js:1026:11)
            at exports._exceptionWithHostPort (util.js:1049:20)
            at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
          code: 'ETIMEDOUT',
          errno: 'ETIMEDOUT',
          syscall: 'connect',
          address: '40.112.185.115',
          port: 5671 } +0ms
          amqp10:client disconnected +16ms
          amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms

With `wss` as protocol:

          > node amq2.js config.json
          uri:wss://iothubowner:xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyyyyyyyy.servicebus.windows.net
            amqp10:client connecting to: wss://iothubowner:xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyyyyyyyy.servicebus.windows.net +0ms
            amqp10:connection Transitioning from DISCONNECTED to START due to connect +31ms
            amqp10:connection Error from socket: Error: Invalid handshake: invalid first line format +739ms
            amqp10:client connection error:  Error: Invalid handshake: invalid first line format
              at Connection.checkHandshake (D:\DEV\AZURE\IOTHUB\amq\node_modules\nodejs-websocket\Connection.js:375:22)
              at Connection.readHandshake (D:\DEV\AZURE\IOTHUB\amq\node_modules\nodejs-websocket\Connection.js:331:54)
              at Connection.doRead (D:\DEV\AZURE\IOTHUB\amq\node_modules\nodejs-websocket\Connection.js:246:13)
              at TLSSocket.<anonymous> (D:\DEV\AZURE\IOTHUB\amq\node_modules\nodejs-websocket\Connection.js:66:8)
              at emitNone (events.js:86:13)
              at TLSSocket.emit (events.js:185:7)
              at emitReadable_ (_stream_readable.js:433:10)
              at emitReadable (_stream_readable.js:427:7)
              at readableAddChunk (_stream_readable.js:188:13)
              at TLSSocket.Readable.push (_stream_readable.js:135:10)
              at TLSWrap.onread (net.js:542:20) +0ms
            amqp10:client disconnected +0ms
            amqp10:connection Transitioning from START to DISCONNECTED due to error +0ms

**Comment by mbroadst** [comment]
@albhardy I hope you'll bear with me, because I'm the "non-windows" side of the team who made this module. It looks to me that, generally, you are connecting to the wrong address in some way. The first example output above indicates that the remote server simply isn't even responding in any way, while the second output indicates that perhaps you are trying to connect via websockets to a server that is not actually communicating back with the correct protocol.

@pierreca perhaps you could help comment on this?

**Comment by pierreca** [comment]
@mbroadst @albhardy I can confirm that `wss` is the protocol that needs to be used for amqp10 to use the websocket transport but you figured that already. About the handshake error, I'll have to look into it more closely when I get back after the holidays. Either there's a special endpoint, or the websocket library we use doesn't support something event hubs does and we'll have to find an alternate.

**Comment by albhardy** [comment]
Thanks Matt and Pierre for looking into this - really appreciate your help in narrowing down the issue. I posted similar question in [Azure IOT repository](https://github.com/Azure/azure-iot-sdk-node/issues/6) as well (but no response yet) - will continue to keep a look out and give you any update. Meanwhile wishing you all a happy holidays!

**Comment by pierreca** [comment]
We'll be taking care of it on the Event-hubs side (https://github.com/Azure/azure-event-hubs-node/issues/2). there's nothing that need to change in amqp10 to support this. I think this issue can be closed.
