### ISSUE TITLE
Question about no credit

### ISSUE THREAD

**Issue by geoffreysamper** [noodlefrenzy/node-amqp10#286]
Hi, 
I'm using amqp library in and the amqp10-link-cache and sometimes I receive follow error. How would I handle this cause of error?

amqp:link:transfer-limit-exceeded:There is no link credit to accept the delivery

Thx

**Comment by mbroadst** [comment]
@geoffreysamper I'm assuming this is for a receiver link? this looks like the [credit](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/policy.js#L175) function isn't being called. This could happen for a number of reasons:
 * there isn't a defined credit function (by default there is one provided) 
 * messages are not being settled upon receipt (by default we auto settle)
 * ?? something else

Could you give a little more detail about your particular setup? It would also be helpful to see a debug log (specify `DEBUG=amqp*` as an environment variable before running) to see if any other peculiar behavior is present.

**Comment by geoffreysamper** [comment]
So what you mean is that I'm using eventhub and there would be a problem. I will try to simulate it again but i can take a while

**Comment by mbroadst** [comment]
@geoffreysamper no.  We have integration tests that run against EventHub and ServiceBus with no issue, what I'm saying is that its possible that you have a configuration error that is preventing the client from "flowing", and thus refreshing its credits

**Comment by geoffreysamper** [comment]
Ok and the only thing you need is the the debug information

**Comment by mbroadst** [comment]
Yes that would be useful, but also if you could provide more information on whether you modifying the default policy, or if you've opted to not use auto-settle and therefore are not manually sending disposition information for received messages.

**Comment by geoffreysamper** [comment]
I copied the the content of event policy because of the pullrequest with the encoder 

https://gist.github.com/geoffreysamper/ba994b545bd64ab48de39047b1791be8

**Comment by geoffreysamper** [comment]
Hi, 

I found the issue with the reason was the the policy was not on setteld. Thanks for the response

**Comment by mbroadst** [comment]
@geoffreysamper cool, glad that wasn't too hard to figure out :)

**Comment by geoffreysamper** [comment]
I can you leave it open I still have the issue. But difficult to simulate I will try it in the next couple of days

**Comment by mbroadst** [comment]
Sorry about that, we'll leave it open until you close it

**Comment by geoffreysamper** [comment]
I can't simulate the bug for the moment. The next couple of weeks I will do more stress testing. May then i can resimulate it. So for now you can close the issue for me.

Thx

**Comment by geoffreysamper** [comment]
Hi, 
I was able to resolve the situation on a production site. When I ran a stress test after a while I got follow error

```
 Error during sending to eventhub webview @error(29) [condition='amqp:link:transfer-limit-exceeded' description='There is no link credit to accept the delivery (id=16004).' info={}]
```
What I think is that my server gets to many requests and can't follow sending the messages to eventhub.  How could I resolve this kind of issue so that I don't loose any messages.

**Comment by geoffreysamper** [comment]
I called MS support and it would be that I send to many message so I have to increase my throughput units
