### ISSUE TITLE
ActiveMQ delayed messages

### ISSUE THREAD

**Issue by klexxp** [noodlefrenzy/node-amqp10#292]
Hi,

is it possible to send the 'AMQ_SCHEDULED_DELAY' property on a message?
And if, how would that look like.

Thanks

**Comment by klexxp** [comment]
I think I found it

https://issues.apache.org/jira/browse/AMQ-6037

**Comment by klexxp** [comment]
I'm sorry to open this up again.

I activated the scheduler in the server, which works when sending messages through the web interface. 

````
var options = { annotations: { 'x-opt-delivery-delay': 10000 }};
return sender.send({ key: "Value" }, options);
```

When I try it like this, the message gets returned immediately. Am I totally wrong?

Thanks

**Comment by klexxp** [comment]
I'm sorry to open this up again.

I activated the scheduler in the server, which works when sending messages through the web interface. 

```
var options = { annotations: { 'x-opt-delivery-delay': 10000 }};
return sender.send({ key: "Value" }, options);
```

When I try it like this, the message gets returned immediately. Am I totally wrong?

Thanks

**Comment by mbroadst** [comment]
@klexxp that looks correct, for completeness sake could you provide the raw hex of the data sent when you send that message? (enable debug mode by specifying the environment variable `DEBUG=amqp*`).  Perhaps ActiveMQ requires it to be encoded differently?

**Comment by klexxp** [comment]
Oh, that would make sense.

```
  amqp10:framing sending frame:  @begin(17) [remoteChannel=null nextOutgoingId=1 incomingWindow=100 outgoingWindow=100 handleMax=4294967295 offeredCapabilities=null desiredCapabilities=null properties={}] +3ms
  amqp10:trace raw: [0000001f02000001005311c012084052015264526470ffffffff4040c10100] +1ms
```

[debug_log.txt](https://github.com/noodlefrenzy/node-amqp10/files/761987/debug_log.txt)

**Comment by mbroadst** [comment]
@klexxp can you try running this instead:
```
var message = {
  annotations: { 'x-opt-delivery-delay': 10000 },
  body: { key: "Value" } 
};

return sender.send(message);
```

**Comment by mbroadst** [comment]
oh doh, scratch all of that. There is no such thing as `annotations`, they are either `deliveryAnnotations` or `messageAnnotations` (I _believe_ JMS calls `messageAnnotations` just `annotations`, but please don't quote me here).

**Comment by klexxp** [comment]
It worked using `messageAnnotations`.

Thank you very much.
