### ISSUE TITLE
Latest versions won't accept custom event hubs errors

### ISSUE THREAD

**Issue by pierreca** [noodlefrenzy/node-amqp10#293]
Some custom event hubs AMQP errors (such as `com.microsoft:argument-out-of-range` when trying to connect to a non-existing partition) get swallowed. This is a breaking change, and as far as I can tell there's no way for the client to know what happened, the connection is just killed with an EncodingError that masks the real cause.
This is due to the changes in `connection.js` in this commit: https://github.com/noodlefrenzy/node-amqp10/commit/5455179ab61cf40171525d422a4648b85dedeff0

Also, it seems there's an issue with the way `error.js` is required in `types/amqp_error.js`, which leads to the `throw` on line 8 to throw a `TypeError: errors.EncodingError is not a constructor` instead of an actual `EncodingError` (at least, this happens with node 6. 
Easiest fix for this is to use `module.exports.` wherever `errors.` is used in `errors.js` and get rid of the local `errors` variable alltogether.. not elegant but it works...

Unfortunately this is blocking the Event Hubs SDK from upgrading to the latest version of the library :-/

**Comment by mbroadst** [comment]
@pierreca can you explain why you think the error was introduced there? To me it seems far more likely that an error frame is being received, however it has an unknown `ErrorCondition` and therefore we're not wrapping it properly.  It would be incredibly helpful to have e.g. the hex for the data representing that error frame so we could create a unit test for it. The `EncodingError` makes me feel like something more nefarious is going on, but it might be data accidentally left in the buffer as well. Do you have a way to reproduce this in a unit test?

**Comment by mbroadst** [comment]
@pierreca ah sorry I found the culprit, you're talking about this: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/types/amqp_error.js#L7. Yeah that totally looks like a bug if MS is using custom errors, I had read the spec to indicate that they only wanted to support the listed error conditions. Again it would be very helpful if you could provide a sample custom error, we can get this pushed in today

**Comment by mbroadst** [comment]
@pierreca for your local testing, it might be enough to replace the `throw new errors.EncodingError...` there with `return value;`

**Comment by pierreca** [comment]
Here's what I believe is the sample error trace for the unit test:
```
0000013b02000000005316d00000012b00000003434100531dd00000011d00000003a323636f6d2e6d6963726f736f66743a617267756d656e742d6f75742d6f662d72616e6765a1f15468652073706563696669656420706172746974696f6e20697320696e76616c696420666f7220616e204576656e7448756220706172746974696f6e2073656e646572206f722072656365697665722e2049742073686f756c64206265206265747765656e203020616e6420372e0d0a506172616d65746572206e616d653a20506172746974696f6e496420547261636b696e6749643a66393365393966643264666234366461383366353662633133633933636162635f47332c2053797374656d547261636b65723a67617465776179362c2054696d657374616d703a322f372f3230313720373a31383a303120504d40
```
