### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by geoffreysamper** [noodlefrenzy/node-amqp10#300]
Hi @mbroadst, 

Any idea when you will create a new release that fixes the issue with the link credit. PS: I don't know that it is alright to ask questions for new release via issues

**Comment by mbroadst** [comment]
@geoffreysamper I was holding off until I could sign off on some "translator-encoder" changes I wanted to integrate, however it's fine to push the patch release now before integrating that PR.

**Comment by mbroadst** [comment]
pushed in 95446a9628d3eb0f405e1a12211c0d48595bfc15
