### ISSUE TITLE
proxy server

### ISSUE THREAD

**Issue by sebastus** [noodlefrenzy/node-amqp10#306]
A potential customer wants to use the module on prem, behind a proxy server. This doesn't work - I found issue #191 and see that it wasn't a priority at the time. Has anything changed?

**Comment by mbroadst** [comment]
@sebastus Can you expand upon your actual use case? Proxying is generally not handled at the driver level like this, but having said that we have pluggable transports. For instance, I created a transport that operates on a character device in order to proxy AMQP over a serial port.

**Comment by sebastus** [comment]
I don't know much about proxying nor do I know much about the customer environment. So I don't know what to tell you. I can only say that their expectation is that I will insert the address of their proxy server into my software and rather than attempting to talk directly to event hub, I'll talk to the proxy server and it will connect to event hub in turn. All SSL. So HTTPS tunneling. I can see how to do this with 'request'. But that's about it.

**Comment by mbroadst** [comment]
@sebastus I can confirm that if you point the driver at an address it will attempt to connect to it using the AMQP 1.0 protocol. If they put a proxy on that address that proxies to some other EH/SB that seems like a devops problem on that side. The driver will not do anything internally to try an determine if there is a proxy, or do some sort of discovery etc.  As I said, if you have a special circumstance we allow for custom transports to be written.  

I'm going to close this issue for now, please reopen it if/when you have more information.
