### ISSUE TITLE
How to detect invalid queue name

### ISSUE THREAD

**Issue by MorganLindqvist** [noodlefrenzy/node-amqp10#309]
I have a small Node JS application using the amqp10 library. The issue I have is that if the queue name I try to connect to does not exist the amqp10 library swallows the error and my application is stuck waiting for a response.

The code I use is the following:

```
client.connect(uri)
  .then(function () {
    return Promise.all([
      client.createSender(invalidTopicName),
      client.createReceiver(invalidTopicName2)
    ]);
  })
  .spread(function(sender, receiver) {
    // error handling
    sender.on('errorReceived', sendError);
    receiver.on('errorReceived', recvError);

    // message event handler
    receiver.on('message', newMessage);

    // send test message
    return sender.send({ DataString: 'from node', DataValue: msgVal }).then(function(state) {
      // this can be used to optionally track the disposition of the sent message
      console.log('state: ', state);
    });
  })
  .error(function (e) {
    console.warn('connection error: ', e);
  });
```

What should I do to get a notification about that the queue does not exist? The spread function is called when both create have failed. (In my case either non or both fails).

**Comment by noodlefrenzy** [comment]
Can you set `DEBUG=amqp*` and take a look at the data you're getting back from the server? I'm curious what it's sending back and when it's telling you about the invalid queue name.

**Comment by mbroadst** [comment]
@MorganLindqvist you should be able to receive the error from listening to the `errorReceived` event of the main client. This was preserved legacy behavior, but I wouldn't be against having it actually emit an `error` (and therefore halt execution) - I have definitely been bit by this before!

**Comment by MorganLindqvist** [comment]
@mbroadst, thanks. The event to listen to was the AMQPClient.ErrorReceived event which mapped to the string 'client:errorReceived'

**Comment by mbroadst** [comment]
@MorganLindqvist bah yeah, I think this would really be better resolved by having everything go back to using `error`, there are a lot of confusing event names here. Sorry about that.
