### ISSUE TITLE
simple_eventhub_test.js not working

### ISSUE THREAD

**Issue by lipp** [noodlefrenzy/node-amqp10#310]
Hi!

Thanks for providing this project!

I cannot get the `simple_eventhub_test.js` running.

The script starts (well i guess) but never ends and does not show up anything on console.
I think the problem is the same as here: https://github.com/Azure/azure-event-hubs-node/issues/23

If my setup is wrong I'd expect to see some error... I am pretty clueless.

**Comment by mbroadst** [comment]
@lipp Hi, can you please paste your debug logs? Please see the README.md for instructions.

**Comment by lipp** [comment]
Got it 😱My messy company network blocked the port. 

Everything is working fine! Sorry for wasting your time!
