### ISSUE TITLE
Settle mode policy configuration broken

### ISSUE THREAD

**Issue by princjef** [noodlefrenzy/node-amqp10#313]
Starting in version 3.5.1 (specifically [this commit](https://github.com/noodlefrenzy/node-amqp10/commit/f3c4617)), the `receiverSettleMode` and `senderSettleMode` policy configuration options no longer set the receiver and sender settle modes correctly, causing them to fall back to their default values.

It makes sense to support the names from the AMQP spec (`rcvSettleMode` and `sndSettleMode`), but we should at least internally translate values under the old names to the new ones until the next major version to maintain backwards compatibility for custom policies

**Comment by princjef** [comment]
It also seems like the default sender mode has changed from `mixed` to `settled` between 3.5.0 and 3.5.1. I could be wrong, but I don't see anywhere where

**Comment by mbroadst** [comment]
@princjef sorry this maybe should have been a major bump. We encountered the issues in #312, and I was trying to correct some sins of the past. I'll commit a fix supporting the old names.

**Comment by princjef** [comment]
Yeah I'm not sure about `rcvSettleMode`, since service bus at least seemed to accept the other form. As for `sndSettleMode`, I'm thinking that it just fell back to the default, since I work with `mixed` mode, but never overrode the value in the policy, which is `settled`

**Comment by princjef** [comment]
Either way, the change in 3.5.2 looks good. Thanks for the quick fix
