### ISSUE TITLE
Queue not automatically created

### ISSUE THREAD

**Issue by DominicBoettger** [noodlefrenzy/node-amqp10#359]
Hello.

When creating a receiver or sender the queue is not automatically created in service bus. Is there an option to do this?
I used rabbit with amqplib before and it was possible to create the queues automatically.

Thanks
Dominic

**Comment by amarzavery** [comment]
Nope. This package expects that the queue/topic, etc. is already created. You can create that from the portal. Or you can use the [`azure-arm-sb`](https://www.npmjs.com/package/azure-arm-sb) package to create the entities programmatically.

**Comment by DominicBoettger** [comment]
Hi

Thank you. That helped me a lot.

Best
Dominic
