### ISSUE TITLE
AMQPClient should support more than one connection

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp10#37]
Would be nice if, once send/receive supported URIs and not just source/target, we could manage multiple connections to different hosts from a single client (e.g. rx from bus1, tx to bus2).

**Comment by noodlefrenzy** [comment]
This is really not worth supporting - they can just instantiate multiple clients.

**Comment by mbroadst** [comment]
yeah I wondered why you had this, it works quite well with multiple instances of AMQPClient :smile:

**Comment by noodlefrenzy** [comment]
My mind works in mysterious ways.
