### ISSUE TITLE
JBoss ActiveMQ Topics not working 

### ISSUE THREAD

**Issue by hverma11** [noodlefrenzy/node-amqp10#48]
Hi, I tried using the topics but it always create the producers and consumers under queue in JBoss ActiveMQ.

Can you please have alook and confirm the exact usage ?

**Comment by hverma11** [comment]
Hi noodlefrenzy,

 Hope you are back. Did you get chance to look into the above mentioned issue.

**Comment by mbroadst** [comment]
@hverma11 you need to use the (sort of weird) activemq uri syntax for topics, like so:

```
  var self = this;
  self.client.connectAsync('amqp://user:pass@host'/)
    .then(function() {
      self.client.receive('topic://my.special.topic', function (err, payload, annotations) {
        // do something
      });
```
