### ISSUE TITLE
Removing received messages from queue

### ISSUE THREAD

**Issue by santanubasu** [noodlefrenzy/node-amqp10#50]
When used with apache activemq, the amqp client does not seem to cause received messages to be removed from the queue, even when the policy sets the receiver settle mode to auto.  I think you may have touched on this in one of your caveats on the project page, but is there a workaround for this at the moment?

**Comment by midramas** [comment]
I'm facing the same issue. No acknowledgment is sent to the broker and therefore after 100 message no messages are received anymore :( Is there something you can do, because the only other option would be for me to add this functionality and I'm really not that good in JS ;)

**Comment by noodlefrenzy** [comment]
Ugh, ActiveMQ can bite my ass.  I just modified the code to send Disposition frames accepting messages, and it STILL doesn't consider them acknowledged and stops after 100.

Sorry, it'll take me a bit longer to figure out what it's complaining about and how to fix it.

**Comment by midramas** [comment]
Thanks for trying! Would be really great for this work as we are using it in a very important project.

**Comment by noodlefrenzy** [comment]
I've started working on it in the 'send-dispo-frames' branch, in case you want to follow along.

**Comment by mbroadst** [comment]
@midramas this should be solved in this [branch](https://github.com/noodlefrenzy/node-amqp10/tree/message-dispositions) which should be merged soon. Please give it a shot and let us know how it works for you. I'm generally working on message disposition, so we should be able to clear up a lot of these issues

**Comment by midramas** [comment]
I've tested it and it works now! Thanks soooo much for that :)

**Comment by mbroadst** [comment]
cool :)
