### ISSUE TITLE
call for documentation on message properties

### ISSUE THREAD

**Issue by mbroadst** [noodlefrenzy/node-amqp10#83]
Surprised I haven't run into this earlier, but how exactly does one specify message properties? Are they just batched in with the annotations parameter of send? Annotations seems a little non-specific, as it could be delivery annotations, message annotations, or properties (?). Just wanted to open the floor for discussion here :smile:

**Comment by mbroadst** [comment]
Looks like [Message](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/types/message.js#L351) already supports them, but there's no way to really send them since the AMQPClient's [send](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/amqp_client.js#L237) creates its own every time. Perhaps it would be better to allow the first value "msg" to be either an object/text or an instance of Message?

**Comment by noodlefrenzy** [comment]
I like that idea.  I was trying to divorce the clients from having to know anything about the underlying implementations at all, really, but perhaps I went too far.  It seems like allowing clients to pass in a built Message object gives clients who need that flexibility the ability to use it, while not harming existing clients.

**Comment by mbroadst** [comment]
fixed in #87, options (including annotations, properties, and application properties) are able to be passed into the send method now, as well as passed back with the receive callback
